### ISSUE TITLE
Multiple `zfs list` commands can slow down your system

### ISSUE THREAD

**Issue by sthorsen** [cego/zfs-cleaner#11]
Hi

In the function `processAll`, there is a loop that will result in many `zfs list` one pr. plan/paths.

On a system with plenty disks, ssd cache, zil logs nvme, memory and CPU. Normal load is 4.

We have around 2000 - 3000 snapshots spread on 50 zpools. When we run zfs-cleaner it takes up to an hour to gather all information it needs before starting destroying snapshots. It might be an idea to make one list and work from there?

**Comment by abrander** [comment]
This sound reasonable. I see someone already thought of it :-)

https://github.com/cego/zfs-cleaner/blob/c2e77b1cb0e46b31fe85ab54948a61aea27418a2/main.go#L50
